FROM golang:1.14.2

ARG USER_ID
ARG USER_NAME
ARG GROUP_ID
ARG GROUP_NAME

RUN if [ $USER_NAME != 'root' ]; then \
        addgroup -gid $GROUP_ID $GROUP_NAME; \
        adduser --disabled-password -gecos "" -uid $USER_ID -gid $GROUP_ID $USER_NAME; \
    fi

WORKDIR /usr/src/app

COPY ./install_prerequisites.sh ./install_prerequisites.sh

RUN chmod +x ./install_prerequisites.sh&& /bin/bash ./install_prerequisites.sh

USER ${USER_NAME}:${GROUP_NAME}
COPY ./ ./

RUN mv /usr/src/app/env/.env.01 /usr/src/app/.env 

CMD ["/bin/bash", "./start.sh"]